theme: jekyll-theme-slate
title: IoT-Router Convention
description: An agreement between interested parties covering positions, definitions and specifications for multiple Smart Living Applications und Internet Access on a single box.
